#!/bin/bash
# @generated by scripts/generate-contract-constants.mjs from shared/contracts/whitelist-format.contract.json. Do not edit by hand - run `npm run contract:constants` at the OpenPath repo root.

# shellcheck disable=SC2034  # consumed by scripts that source this library
OPENPATH_CONTRACT_DISABLED_SENTINEL='#DESACTIVADO'
# shellcheck disable=SC2034
OPENPATH_CONTRACT_DISABLED_SENTINEL_WORD='DESACTIVADO'
# shellcheck disable=SC2034
OPENPATH_CONTRACT_SECTION_WHITELIST='## WHITELIST'
# shellcheck disable=SC2034
OPENPATH_CONTRACT_SECTION_BLOCKED_SUBDOMAINS='## BLOCKED-SUBDOMAINS'
# shellcheck disable=SC2034
OPENPATH_CONTRACT_SECTION_BLOCKED_PATHS='## BLOCKED-PATHS'
# shellcheck disable=SC2034
OPENPATH_CONTRACT_SECTION_ALLOWED_PATHS='## ALLOWED-PATHS'

get_openpath_contract_captive_portal_probe_domains() {
    cat <<'EOF'
detectportal.firefox.com
connectivity-check.ubuntu.com
captive.apple.com
www.msftconnecttest.com
clients3.google.com
EOF
}
