<##
.SYNOPSIS
    External disposable-Windows controller that drives a Proxmox lab.
.DESCRIPTION
    Implements the run-windows-desktop-survival controller contract for one
    phase. The lab inventory and transport live in an operator-owned JSON file
    outside the repository (OPENPATH_DESKTOP_LAB_CONFIG, default
    ~/.config/openpath/desktop-survival-lab.json); no hostnames, VM IDs or
    credentials are committed here.

    Exit codes:
      0  phase passed and a correlated observation was written
      1  phase failed (transport, protocol or verification error)
      2  BLOCKED_PLATFORM_VALIDATION (platform or lab configuration missing)

    This phase only performs transport dry-runs. It never claims acceptance:
    observations are marked dryRun=true and acceptanceEligible=false, and the
    Pro/Education desktop-survival matrix stays blocked until the in-guest
    interactive harness exists.
.PARAMETER PayloadPath
    Controller payload written by DisposableWindowsTarget (run/attempt/scenario
    identity, artifact paths and hashes, output path).
.PARAMETER OutputPath
    Correlated observation file to write for this phase.
.PARAMETER Mode
    Controller phase: Prepare, Observe, AfterReboot or Cleanup.
.PARAMETER RunId
    Workflow run identifier.
.PARAMETER RunAttempt
    Workflow run attempt.
.PARAMETER ScenarioId
    Desktop-survival scenario identifier (must exist in the lab config).
.PARAMETER CorrelationNonce
    Per-phase correlation nonce generated by the adapter.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$PayloadPath,
    [Parameter(Mandatory = $true)][string]$OutputPath,
    [Parameter(Mandatory = $true)][ValidateSet('Prepare', 'Observe', 'AfterReboot', 'Cleanup')][string]$Mode,
    [Parameter(Mandatory = $true)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$')][string]$RunId,
    [Parameter(Mandatory = $true)][ValidateRange(1, 2147483647)][int]$RunAttempt,
    [Parameter(Mandatory = $true)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$')][string]$ScenarioId,
    [Parameter(Mandatory = $true)][ValidatePattern('^[0-9a-fA-F]{32}$')][string]$CorrelationNonce
)

$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'ProxmoxWindowsLab.psm1') -Force

function Get-OpenPathLabCanonicalPhase {
    param([Parameter(Mandatory = $true)][string]$Value)
    switch ($Value) {
        'Prepare' { return 'prepare' }
        'Observe' { return 'observe' }
        'AfterReboot' { return 'afterReboot' }
        'Cleanup' { return 'cleanup' }
        default { throw 'desktop-lab-payload-invalid' }
    }
}

function Write-OpenPathLabJsonAtomic {
    param([Parameter(Mandatory = $true)][string]$Path, [Parameter(Mandatory = $true)][object]$Value)
    $parent = Split-Path -Parent $Path
    if ($parent -and -not (Test-Path -LiteralPath $parent -PathType Container)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }
    $temporary = "$Path.$([guid]::NewGuid().ToString('N')).tmp"
    try {
        [IO.File]::WriteAllText($temporary, ($Value | ConvertTo-Json -Depth 30), [Text.UTF8Encoding]::new($false))
        Move-Item -LiteralPath $temporary -Destination $Path -Force -ErrorAction Stop
    }
    finally { Remove-Item -LiteralPath $temporary -Force -ErrorAction SilentlyContinue }
}

$phase = Get-OpenPathLabCanonicalPhase -Value $Mode
try {
    $payload = Get-Content -LiteralPath $PayloadPath -Raw -ErrorAction Stop | ConvertFrom-Json -ErrorAction Stop
}
catch {
    [Console]::Error.WriteLine('CONTROLLER_PHASE_FAILED: desktop-lab-payload-invalid')
    exit 1
}

$configPath = if ($env:OPENPATH_DESKTOP_LAB_CONFIG) { [string]$env:OPENPATH_DESKTOP_LAB_CONFIG } else { Join-Path ([Environment]::GetFolderPath('UserProfile')) '.config/openpath/desktop-survival-lab.json' }
try {
    $config = Read-OpenPathProxmoxLabConfig -Path $configPath
    $transport = New-OpenPathProxmoxLabTransport -Config $config
    $result = Invoke-OpenPathProxmoxControllerPhase -Payload $payload -Config $config -Transport $transport
    Write-OpenPathLabJsonAtomic -Path $OutputPath -Value $result
    exit 0
}
catch {
    $message = ([string]$_.Exception.Message).Trim()
    $code = $message
    if ($message -match '^([a-z0-9][a-z0-9-]*)') { $code = $Matches[1] }
    if (Test-OpenPathLabBlockedErrorCode -Code $code) {
        $blocked = [pscustomobject][ordered]@{
            schemaVersion    = 2
            status           = 'blocked'
            runId            = $RunId
            runAttempt       = $RunAttempt
            scenarioId       = $ScenarioId
            phase            = $phase
            correlationNonce = $CorrelationNonce
            reasonCode       = $code
        }
        Write-OpenPathLabJsonAtomic -Path $OutputPath -Value $blocked
        [Console]::Error.WriteLine("BLOCKED_PLATFORM_VALIDATION: $code")
        exit 2
    }
    [Console]::Error.WriteLine("CONTROLLER_PHASE_FAILED: $code")
    exit 1
}
