function ConvertTo-AcrylicHostsContent {
    # serializes a hosts definition object into a complete acrylic hosts text file with section headers and a trailing newline.
    [CmdletBinding()]
    param([Parameter(Mandatory = $true)][pscustomobject]$Definition)

    $lines = @(
        '# ========================================',
        '# OpenPath DNS - Generated by openpath-windows',
        "# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
        "# Upstream DNS: $($Definition.UpstreamDNS)",
        '# ========================================',
        ''
    )

    foreach ($section in @($Definition.Sections)) {
        $lines += '# ========================================'
        $lines += "# $($section.Title)"
        if ($section.Description) { $lines += "# $($section.Description)" }
        $lines += '# ========================================'
        $lines += ''
        $sectionLines = @($section.Lines)
        if ($sectionLines.Count -gt 0) { $lines += $sectionLines }
        $lines += ''
    }

    return (($lines -join "`n").TrimEnd() + "`n")
}

function Get-AcrylicHostsEffectiveContent {
    # strips the volatile `# Generated:` header from a rendered hosts text so two
    # renders of the same effective content compare equal.
    [CmdletBinding()]
    param([AllowEmptyString()][string]$Content = '')

    return (@($Content -split "`n" | Where-Object { $_ -notmatch '^# Generated: ' }) -join "`n")
}

function Test-AcrylicHostsContentEquivalent {
    # compares two rendered hosts contents ignoring the generated timestamp line.
    [CmdletBinding()]
    param(
        [AllowEmptyString()][string]$Left = '',
        [AllowEmptyString()][string]$Right = ''
    )

    return ((Get-AcrylicHostsEffectiveContent -Content $Left) -eq (Get-AcrylicHostsEffectiveContent -Content $Right))
}
