function ConvertTo-AcrylicHostsContent {
    # serializes a hosts definition object into a complete acrylic hosts text file with section headers and a trailing newline.
    [CmdletBinding()]
    param([Parameter(Mandatory = $true)][pscustomobject]$Definition)

    $lines = @(
        '# ========================================',
        '# OpenPath DNS - Generated by openpath-windows',
        "# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
        "# Upstream DNS: $($Definition.UpstreamDNS)",
        '# ========================================',
        ''
    )

    foreach ($section in @($Definition.Sections)) {
        $lines += '# ========================================'
        $lines += "# $($section.Title)"
        if ($section.Description) { $lines += "# $($section.Description)" }
        $lines += '# ========================================'
        $lines += ''
        $sectionLines = @($section.Lines)
        if ($sectionLines.Count -gt 0) { $lines += $sectionLines }
        $lines += ''
    }

    return (($lines -join "`n").TrimEnd() + "`n")
}
