// @generated by scripts/generate-contract-constants.mjs from shared/contracts/whitelist-format.contract.json. Do not edit by hand - run `npm run contract:constants` at the OpenPath repo root.

/** First-line marker that disables enforcement for a whitelist.txt document. */
export const WHITELIST_DISABLED_SENTINEL = '#DESACTIVADO';

/** Section headers of the whitelist.txt wire format, in canonical emit order. */
export const WHITELIST_SECTION_HEADERS = {
  whitelist: '## WHITELIST',
  blockedSubdomains: '## BLOCKED-SUBDOMAINS',
  blockedPaths: '## BLOCKED-PATHS',
  allowedPaths: '## ALLOWED-PATHS',
} as const;

/** Captive-portal probe domains the Linux agent must keep resolvable. */
export const LINUX_CAPTIVE_PORTAL_PROBE_DOMAINS = [
  'detectportal.firefox.com',
  'connectivity-check.ubuntu.com',
  'captive.apple.com',
  'www.msftconnecttest.com',
  'clients3.google.com',
] as const;

/** Captive-portal probe domains the Windows agent must keep resolvable. */
export const WINDOWS_CAPTIVE_PORTAL_PROBE_DOMAINS = [
  'detectportal.firefox.com',
  'connectivity-check.ubuntu.com',
  'captive.apple.com',
  'www.msftconnecttest.com',
  'msftconnecttest.com',
  'clients3.google.com',
] as const;

/** Subset of probe domains Windows captive-portal recovery may open (W-3). */
export const WINDOWS_CAPTIVE_PORTAL_DETECTION_HOSTS = [
  'www.msftconnecttest.com',
  'msftconnecttest.com',
  'detectportal.firefox.com',
  'clients3.google.com',
] as const;
